// ------------------------------------------------------------------------------
// <auto-generated>
// 此代码由工具生成。
// 运行时版本:4.0.30319.42000
// 
// 对此文件的更改可能会导致不正确的行为，并且如果
// 重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------


using System.Diagnostics;
using Microsoft.VisualBasic;

namespace PCL.My.Resources
{

    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    /// <summary>
    /// 一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [DebuggerNonUserCode()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    [HideModuleName()]
    internal static class Resources
    {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        /// 返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(resourceMan, null))
                {
                    var temp = new System.Resources.ResourceManager("PCL.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        /// 重写当前线程的 CurrentUICulture 属性，对
        /// 使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// 查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Custom
        {
            get
            {
                var obj = ResourceManager.GetObject("Custom", resourceCulture);
                return (byte[])obj;
            }
        }

        /// <summary>
        /// 查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] ForgeInstaller
        {
            get
            {
                var obj = ResourceManager.GetObject("ForgeInstaller", resourceCulture);
                return (byte[])obj;
            }
        }

        /// <summary>
        /// 查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Help
        {
            get
            {
                var obj = ResourceManager.GetObject("Help", resourceCulture);
                return (byte[])obj;
            }
        }

        /// <summary>
        /// 查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] JavaWrapper
        {
            get
            {
                var obj = ResourceManager.GetObject("JavaWrapper", resourceCulture);
                return (byte[])obj;
            }
        }

        /// <summary>
        /// 查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] libwebp64
        {
            get
            {
                var obj = ResourceManager.GetObject("libwebp64", resourceCulture);
                return (byte[])obj;
            }
        }

        /// <summary>
        /// 查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] ModData
        {
            get
            {
                var obj = ResourceManager.GetObject("ModData", resourceCulture);
                return (byte[])obj;
            }
        }

        /// <summary>
        /// 查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Transformer
        {
            get
            {
                var obj = ResourceManager.GetObject("Transformer", resourceCulture);
                return (byte[])obj;
            }
        }
    }
}